name: Build PyHLS Image

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
    tags:
      - 'latest'

permissions: 
  contents: read
  packages: write
  
jobs:
  build-pyhls:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Docker Hub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}
      - name: Docker meta
        id: meta_pyhls
        uses: docker/metadata-action@v3
        with:
          images: |
            docker.io/zingytomato/pyhls
          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64,linux/arm64, linux/arm/v7
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta_pyhls.outputs.tags }}
          labels: ${{ steps.meta_pyhls.outputs.labels }}